name: Run R script to get Google Scholar citations

on:
  schedule:
    - cron: '0 23 * * 5'
  push:

permissions:
  contents: write-all

jobs:
  render:
    name: Execute action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Run script
        run: Rscript R/get_citations.R
